name: task_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  json_annotation: ^4.0.1

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  http: ^1.2.1
  data_connection_checker_nulls: ^0.0.2


dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^2.0.2

  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true

  assets:
  
    - assets/


  
